parameters:
    hg_email.mail_builder.class: 'Hgabka\EmailBundle\Helper\MailBuilder'
    hg_email.message_logger.class: 'Hgabka\EmailBundle\Logger\MessageLogger'
    hg_email.message_sender.class: 'Hgabka\EmailBundle\Helper\MessageSender'
    hg_email.queue_manager.class: 'Hgabka\EmailBundle\Helper\QueueManager'
    hg_email.recipient_manager.class: 'Hgabka\EmailBundle\Helper\RecipientManager'
    hg_email.template_type_manager.class: 'Hgabka\EmailBundle\Helper\TemplateTypeManager'

services:
    hg_email.admin.email_template:
        class: Hgabka\EmailBundle\Admin\EmailTemplateAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, group: hg_email.group, icon: '<i class="fa fa-envelope"></i>', label: hg_email.admin.email_template.label, label_catalogue: 'HgabkaEmailBundle', label_translator_strategy: 'sonata.admin.label.strategy.underscore' }
        arguments: [null, Hgabka\EmailBundle\Entity\EmailTemplate, HgabkaEmailBundle:EmailTemplateAdmin]
        calls:
          - [setBuilder, ["@hg_email.mail_builder"]]
          - [setTemplateTypeManager, ["@hg_email.template_type_manager"]]
          - [setAuthChecker, ["@security.authorization_checker"]]
          - [ setTemplate, ['edit', '@@HgabkaEmail/Admin/edit.html.twig']]

    hg_email.recipient_manager:
        class: '%hg_email.recipient_manager.class%'
        arguments: ["@doctrine", "@translator", "@form.factory", "@hg_email.template_type_manager"]

    hg_email.template_type_manager:
        class: '%hg_email.template_type_manager.class%'
        arguments: ["@doctrine", "@translator", "@hgabka_utils.hgabka_utils"]

    hg_email.recipient_type.default:
        class:  Hgabka\EmailBundle\Recipient\DefaultRecipientType
        tags:
        - { name: hg_email.recipient_type }
        arguments: ["@hg_email.mail_builder", "@translator"]
        public: false
        calls:
        - [setManager, ["@hg_email.recipient_manager"]]
        - [setTranslator, ["@translator"]]

    hg_email.recipient_type.general:
        class:  Hgabka\EmailBundle\Recipient\GeneralRecipientType
        tags:
        - { name: hg_email.recipient_type }
        arguments: ["@hgabka_utils.hgabka_utils", "@translator"]
        public: false
        calls:
        - [setManager, ["@hg_email.recipient_manager"]]
        - [setTranslator, ["@translator"]]

    hg_email.mail_builder:
        class: '%hg_email.mail_builder.class%'
        arguments: ["@doctrine", "@request_stack", "@hg_email.param_substituter", "@translator", "@hgabka_utils.hgabka_utils", "@router", '@hgabka_media.media_manager', "@hg_email.recipient_manager", "@event_dispatcher", "@hg_email.template_type_manager"]

    hg_email.message_sender:
        class: '%hg_email.message_sender.class%'
        arguments: ["@doctrine", "@mailer", "@hg_email.queue_manager", "@translator", "@hgabka_utils.hgabka_utils", "@hg_email.mail_builder"]

    hg_email.message_logger:
        class: '%hg_email.message_logger.class%'
        arguments: ["@logger", '']

    hg_email.email_logger:
        class: 'Hgabka\EmailBundle\Logger\EmailLogger'
        arguments: ["@doctrine"]

    hg_email.queue_manager:
        class: '%hg_email.queue_manager.class%'
        arguments: ["@doctrine", "@mailer", "@hg_email.message_logger", '', '', '', '', '']
        calls:
            - method: setMailBuilder
              arguments:
                  - "@hg_email.mail_builder"

    hg_email.param_substituter:
        class: 'Hgabka\EmailBundle\Helper\ParamSubstituter'
        arguments: ["@request_stack", "%kernel.cache_dir%", "%kernel.project_dir%", []]

    hg_email.email_subscriber:
        class: Hgabka\EmailBundle\EventListener\EmailSubscriber
        tags:
            - { name: doctrine.event_subscriber, connection: default }

    hg_email.mailer_subscriber:
        class: Hgabka\EmailBundle\EventListener\MailerSubscriber
        arguments: ["@hg_email.email_logger", '']
        tags:
            - { name: kernel.event_subscriber }

    hg_email.mail_logger_plugin:
        class: Hgabka\EmailBundle\Mailer\MessageLoggerPlugin
        arguments: ["@event_dispatcher"]
        tags:
            - { name: "swiftmailer.default.plugin" }

    hg_email.redirect_plugin:
        class: Hgabka\EmailBundle\Mailer\RedirectPlugin
        arguments: [""]
        calls:
            - method: setHgabkaUtils
              arguments:
                  - "@hgabka_utils.hgabka_utils"

            - method: setDebug
              arguments:
                  - "%kernel.debug%"
        tags:
            - { name: "swiftmailer.default.plugin" }


    hg_email.add_headers_plugin:
        class: Hgabka\EmailBundle\Mailer\AddHeadersPlugin
        arguments: ["@event_dispatcher"]
        tags:
            - { name: "swiftmailer.default.plugin" }

    hg_email.add_recipients_plugin:
        class: Hgabka\EmailBundle\Mailer\AddRecipientsPlugin
        tags:
            - { name: "swiftmailer.default.plugin" }

    hg_email.add_return_path_plugin:
        class: Hgabka\EmailBundle\Mailer\AddReturnPathPlugin
        tags:
            - { name: "swiftmailer.default.plugin" }

    hg_email.mailbox_reader:
        class: Hgabka\EmailBundle\Helper\MailboxReader
        arguments: ["@hg_email.email_parser", '', '', '', '', '', 'INBOX', '']

    hg_email.bounce_checker:
        class: Hgabka\EmailBundle\Helper\BounceChecker
        arguments: ["@doctrine", "@hg_email.mailbox_reader"]

    hg_email.email_parser:
        class: Hgabka\EmailBundle\Helper\EmailParser

    hg_email.recipients_type:
        class: Hgabka\EmailBundle\Form\RecipientsType
        arguments: ["@hg_email.recipient_manager", "@hg_email.template_type_manager"]
        tags:
            - { name: form.type }
        public: false

    hg_email.subscriber_type:
        class: Hgabka\EmailBundle\Form\MessageSubscriberAdminType
        arguments: ["@doctrine.orm.entity_manager", "@hgabka_utils.hgabka_utils", "@hg_email.subscription_manager", "@security.authorization_checker"]
        tags:
            - { name: form.type }

    hg_email.message_type:
        class: Hgabka\EmailBundle\Form\MessageAdminType
        arguments: ["@doctrine.orm.entity_manager", "@hg_email.mail_builder", "@security.authorization_checker"]
        tags:
            - { name: form.type }

    hg_email.event_listener.entity_load:
        class: Hgabka\EmailBundle\EventListener\EntityLoadListener
        tags:
            - { name: doctrine.event_listener, event: postLoad }

    hg_email.email_twig_extension:
        class: Hgabka\EmailBundle\Twig\EmailTwigExtension
        arguments: ['@hg_email.mail_builder','@hg_email.param_substituter', '@translator', "@hg_email.recipient_manager","@hg_email.template_type_manager"]
        public: false
        tags:
            - { name: twig.extension }

    hg_email.email_voter:
        class:  Hgabka\EmailBundle\Security\EmailVoter
        arguments: ['@security.access.decision_manager', '']
        tags:
            - { name: security.voter }
        public: false

    hg_email.subscription_manager:
        class: 'Hgabka\EmailBundle\Helper\SubscriptionManager'
        arguments: ["@doctrine", "@hgabka_utils.hgabka_utils", '']

    hg_email.subscriber_subscriber:
        class: Hgabka\EmailBundle\EventListener\SubscriberSubscriber
        arguments: ['@hg_email.subscription_manager']
        tags:
            - { name: doctrine.event_subscriber, connection: default }

    Hgabka\EmailBundle\Helper\MessageSender: "@hg_email.message_sender"
    Hgabka\EmailBundle\Helper\MailBuilder: "@hg_email.mail_builder"
    Hgabka\EmailBundle\Helper\RecipientManager: "@hg_email.recipient_manager"
    Hgabka\EmailBundle\Helper\TemplateTypeManager: "@hg_email.template_type_manager"
