parameters:
    hg_email.mail_builder.class: 'Hgabka\EmailBundle\Helper\MailBuilder'
    hg_email.message_logger.class: 'Hgabka\EmailBundle\Logger\MessageLogger'
    hg_email.message_sender.class: 'Hgabka\EmailBundle\Helper\MessageSender'
    hg_email.queue_manager.class: 'Hgabka\EmailBundle\Helper\QueueManager'
    hg_email.recipient_manager.class: 'Hgabka\EmailBundle\Helper\RecipientManager'
    hg_email.template_type_manager.class: 'Hgabka\EmailBundle\Helper\TemplateTypeManager'

services:
    hg_email.admin.email_template:
        class: Hgabka\EmailBundle\Admin\EmailTemplateAdmin
        tags:
            - { name: sonata.admin, model_class: Hgabka\EmailBundle\Entity\EmailTemplate, controller: Hgabka\EmailBundle\Controller\EmailTemplateAdminController, manager_type: orm, group: hg_email.group, icon: '<i class="fa fa-envelope"></i>', label: hg_email.admin.email_template.label, label_translator_strategy: 'sonata.admin.label.strategy.underscore', translation_domain: 'messages' }
        calls:
            - [setBuilder, ["@hg_email.mail_builder"]]
            - [setTemplateTypeManager, ["@hg_email.template_type_manager"]]
            - [setAuthChecker, ["@security.authorization_checker"]]
            - [ setTemplate, ['edit', '@@HgabkaEmail/Admin/EmailTemplate/edit.html.twig']]

    hg_email.admin.message:
        class: Hgabka\EmailBundle\Admin\MessageAdmin
        tags:
            - { name: sonata.admin, model_class: Hgabka\EmailBundle\Entity\Message, controller: Hgabka\EmailBundle\Controller\MessageAdminController, manager_type: orm, group: hg_email.group, icon: '<i class="fa fa-envelope"></i>', label: hg_email.admin.message.label, label_translator_strategy: 'sonata.admin.label.strategy.underscore', translation_domain: 'messages' }
        calls:
            - [setBuilder, ["@hg_email.mail_builder"]]
            - [setAuthChecker, ["@security.authorization_checker"]]
            - [setTemplate, ['edit', '@@HgabkaEmail/Admin/Message/edit.html.twig']]
            - [setUtils, ["@hgabka_utils.hgabka_utils"]]

    hg_email.admin.email_layout:
        class: Hgabka\EmailBundle\Admin\EmailLayoutAdmin
        tags:
            - { name: sonata.admin, model_class: Hgabka\EmailBundle\Entity\EmailLayout, controller: Hgabka\EmailBundle\Controller\EmailLayoutAdminController, manager_type: orm, group: hg_email.group, icon: '<i class="fa fa-list"></i>', label: hg_email.admin.email_layout.label, label_translator_strategy: 'sonata.admin.label.strategy.underscore', translation_domain: 'messages' }
        calls:
            - [setMailBuilder, ["@hg_email.mail_builder"]]
            - [ setTemplate, ['edit', '@@HgabkaEmail/Admin/EmailLayout/edit.html.twig']]

    hg_email.admin.message_list:
        class: Hgabka\EmailBundle\Admin\MessageListAdmin
        tags:
            - { name: sonata.admin, model_class: Hgabka\EmailBundle\Entity\MessageList, controller: Hgabka\EmailBundle\Controller\MessageListAdminController, manager_type: orm, group: hg_email.group, icon: '<i class="fa fa-list"></i>', label: hg_email.admin.message_list.label, label_translator_strategy: 'sonata.admin.label.strategy.underscore', translation_domain: 'messages'}
        calls:
            - [setManager, ["@hg_email.subscription_manager"]]

    hg_email.admin.subscriber:
        class: Hgabka\EmailBundle\Admin\SubscriberAdmin
        tags:
            - { name: sonata.admin, model_class: Hgabka\EmailBundle\Entity\MessageSubscriber, controller: Hgabka\EmailBundle\Controller\SubscriberAdminController, manager_type: orm, group: hg_email.group, icon: '<i class="fa fa-newspaper"></i>', label: hg_email.admin.subscriber.label, label_translator_strategy: 'sonata.admin.label.strategy.underscore', translation_domain: 'messages' }
        calls:
            - [setManager, ["@hg_email.subscription_manager"]]
            - [setUtils, ["@hgabka_utils.hgabka_utils"]]

    Hgabka\EmailBundle\Helper\RecipientManager:
        public: true
        arguments: ["@doctrine", "@translator", "@form.factory", "@hg_email.template_type_manager", '@Hgabka\EmailBundle\Helper\MailHelper', '']

    hg_email.recipient_manager:
        alias: Hgabka\EmailBundle\Helper\RecipientManager

    hg_email.template_type_manager:
        class: '%hg_email.template_type_manager.class%'
        arguments: ["@doctrine", "@translator", "@hgabka_utils.hgabka_utils"]

    hg_email.email_template_recipient_type.default:
        class:  Hgabka\EmailBundle\Recipient\DefaultEmailTemplateRecipientType
        tags:
        - { name: hg_email.email_template_recipient_type, priority: 100000 }
        arguments: ["@hg_email.mail_builder", "@translator"]
        public: false
        calls:
        - [setManager, ["@hg_email.recipient_manager"]]
        - [setBuilder, ["@hg_email.mail_builder"]]
        - [setTranslator, ["@translator"]]

    hg_email.email_template_recipient_type.general:
        class:  Hgabka\EmailBundle\Recipient\GeneralEmailTemplateRecipientType
        tags:
        - { name: hg_email.email_template_recipient_type, }
        arguments: ["@hgabka_utils.hgabka_utils", "@translator"]
        public: false
        calls:
        - [setManager, ["@hg_email.recipient_manager"]]
        - [setBuilder, ["@hg_email.mail_builder"]]
        - [setTranslator, ["@translator"]]

    hg_email.message_recipient_type.default:
        class:  Hgabka\EmailBundle\Recipient\DefaultMessageRecipientType
        tags:
        - { name: hg_email.message_recipient_type, priority: 0  }
        public: false
        calls:
        - [setManager, ["@hg_email.recipient_manager"]]
        - [setBuilder, ["@hg_email.mail_builder"]]
        - [setTranslator, ["@translator"]]

    hg_email.message_recipient_type.general:
        class:  Hgabka\EmailBundle\Recipient\GeneralMessageRecipientType
        tags:
        - { name: hg_email.message_recipient_type, priority: 0 }
        arguments: ["@hgabka_utils.hgabka_utils"]
        public: false
        calls:
        - [setManager, ["@hg_email.recipient_manager"]]
        - [setBuilder, ["@hg_email.mail_builder"]]
        - [setTranslator, ["@translator"]]

    hg_email.message_recipient_type.subscribers:
        class:  Hgabka\EmailBundle\Recipient\SubscribersMessageRecipientType
        tags:
        - { name: hg_email.message_recipient_type, priority: 10000 }
        arguments: ["@hg_email.subscription_manager", "@hgabka_utils.hgabka_utils", "@router"]
        public: false
        calls:
        - [setManager, ["@hg_email.recipient_manager"]]
        - [setBuilder, ["@hg_email.mail_builder"]]
        - [setTranslator, ["@translator"]]

    hg_email.layout_manager:
        class: Hgabka\EmailBundle\Helper\LayoutManager
        arguments: ['@hgabka_utils.hgabka_utils', '@hg_email.param_substituter', '@twig', '']

    hg_email.mail_builder:
        class: '%hg_email.mail_builder.class%'
        arguments: ['@doctrine', '@request_stack', '@hg_email.param_substituter', '@translator', '@hgabka_utils.hgabka_utils', '@router', '@hgabka_media.media_manager', '@hg_email.recipient_manager', '@event_dispatcher', '@hg_email.template_type_manager', '@hg_email.layout_manager', '@Hgabka\EmailBundle\Helper\MailHelper']

    hg_email.message_sender:
        class: '%hg_email.message_sender.class%'
        arguments: ["@doctrine", "@mailer.mailer", "@hg_email.queue_manager", "@translator", "@hgabka_utils.hgabka_utils", "@hg_email.mail_builder"]

    hg_email.message_logger:
        class: '%hg_email.message_logger.class%'
        arguments: ['']

    hg_email.email_logger:
        class: 'Hgabka\EmailBundle\Logger\EmailLogger'
        arguments: ["@doctrine", '@Hgabka\EmailBundle\Helper\MailHelper', '']

    hg_email.queue_manager:
        class: '%hg_email.queue_manager.class%'
        arguments: ["@doctrine", "@mailer.mailer", "@hg_email.message_logger", '@hg_email.recipient_manager', '@router', '@hgabka_utils.hgabka_utils',  '', '', '', '', '', '', '']
        calls:
            - method: setMailBuilder
              arguments:
                  - "@hg_email.mail_builder"

    hg_email.param_substituter:
        class: 'Hgabka\EmailBundle\Helper\ParamSubstituter'
        arguments: ["@request_stack", "@router", '@Hgabka\EmailBundle\Helper\MailHelper', "%kernel.cache_dir%", "%kernel.project_dir%", []]

    Hgabka\EmailBundle\Helper\ParamSubstituter:
        alias: hg_email.param_substituter

    hg_email.email_subscriber:
        class: Hgabka\EmailBundle\EventListener\EmailSubscriber
        tags:
            - { name: doctrine.event_subscriber, connection: default }

    hg_email.mailer_subscriber:
        class: Hgabka\EmailBundle\EventListener\MailerSubscriber
        arguments: ["@hg_email.email_logger", '']
        tags:
            - { name: kernel.event_subscriber }

    hg_email.message_subscriber_subscriber:
        class: Hgabka\EmailBundle\EventListener\MessageSubscriberEventSubscriber
        arguments: ["@hg_email.recipient_manager"]
        tags:
            - { name: kernel.event_subscriber }

    hg_email.mailbox_reader:
        class: Hgabka\EmailBundle\Helper\MailboxReader
        arguments: ["@hg_email.email_parser", '', '', '', '', '', 'INBOX', '']

    hg_email.bounce_checker:
        class: Hgabka\EmailBundle\Helper\BounceChecker
        arguments: ["@doctrine", "@hg_email.mailbox_reader"]

    hg_email.email_parser:
        class: Hgabka\EmailBundle\Helper\EmailParser

    hg_email.template_recipients_type:
        class: Hgabka\EmailBundle\Form\EmailTemplateRecipientsType
        arguments: ["@hg_email.recipient_manager", "@hg_email.template_type_manager"]
        tags:
            - { name: form.type }
        public: false

    hg_email.message_mail_type:
        class: Hgabka\EmailBundle\Form\MessageMailType
        arguments: ["@hgabka_utils.hgabka_utils"]
        tags:
            - { name: form.type }
        public: false

    hg_email.attachment_type:
        class: Hgabka\EmailBundle\Form\AttachmentType
        arguments: ["@hg_media.admin.media"]
        tags:
            - { name: form.type }
        public: false

    hg_email.message_recipients_type:
        class: Hgabka\EmailBundle\Form\MessageRecipientsType
        arguments: ["@hg_email.recipient_manager"]
        tags:
            - { name: form.type }
        public: false

    hg_email.subscriber_type:
        class: Hgabka\EmailBundle\Form\MessageSubscriberAdminType
        arguments: ["@doctrine.orm.entity_manager", "@hgabka_utils.hgabka_utils", "@hg_email.subscription_manager", "@security.authorization_checker"]
        tags:
            - { name: form.type }

    hg_email.message_type:
        class: Hgabka\EmailBundle\Form\MessageAdminType
        arguments: ["@doctrine.orm.entity_manager", "@hg_email.mail_builder", "@security.authorization_checker"]
        tags:
            - { name: form.type }

    hg_email.event_listener.entity_load:
        class: Hgabka\EmailBundle\EventListener\EntityLoadListener
        tags:
            - { name: doctrine.event_listener, event: postLoad }

    hg_email.email_twig_extension:
        class: Hgabka\EmailBundle\Twig\EmailTwigExtension
        arguments: ['@hg_email.mail_builder','@hg_email.param_substituter', '@translator', "@hg_email.recipient_manager","@hg_email.template_type_manager", "@hg_email.subscription_manager", "@hg_email.layout_manager"]
        public: false
        tags:
            - { name: twig.extension }

    hg_email.email_voter:
        class:  Hgabka\EmailBundle\Security\EmailVoter
        arguments: ['@security.access.decision_manager', '@hg_email.template_type_manager', '']
        tags:
            - { name: security.voter }
        public: false

    hg_email.subscription_manager:
        class: 'Hgabka\EmailBundle\Helper\SubscriptionManager'
        arguments: ["@doctrine", "@hgabka_utils.hgabka_utils", '', '']

    hg_email.subscriber_subscriber:
        class: Hgabka\EmailBundle\EventListener\SubscriberSubscriber
        arguments: ['@hg_email.subscription_manager']
        tags:
            - { name: doctrine.event_subscriber, connection: default }

    Hgabka\EmailBundle\Admin\Menu\AdminMenuListener:
        autowire: true
        arguments: ['@sonata.admin.pool', '@hg_email.subscription_manager','@hg_email.mail_builder']
        tags:
        - { name: kernel.event_listener, event: sonata.admin.event.configure.menu.sidebar, method: addMenuItems }

    hg_email.message_var.webversion:
        class: Hgabka\EmailBundle\Message\WebversionMessageVar
        arguments: ['@router']
        tags:
            - { name: hg_email.message_var, priority: 90 }
        calls:
        - [setTranslator, ["@translator"]]

    hg_email.message_var.unsubscribe_url:
        class: Hgabka\EmailBundle\Message\UnsubscribeUrlMessageVar
        arguments: ['@router', '@hg_email.recipient_manager']
        tags:
            - { name: hg_email.message_var, priority: -253 }
        calls:
        - [setTranslator, ["@translator"]]

    hg_email.message_var.unsubscribe_link:
        class: Hgabka\EmailBundle\Message\UnsubscribeLinkMessageVar
        arguments: ['@router', '@hg_email.recipient_manager']
        tags:
            - { name: hg_email.message_var, priority: -254 }
        calls:
        - [setTranslator, ["@translator"]]

    hg_email.layout_var.content:
        class: Hgabka\EmailBundle\Layout\ContentLayoutVar
        tags:
            - { name: hg_email.layout_var, priority: 90 }
        calls:
        - [setTranslator, ["@translator"]]

    hg_email.layout_var.recipient_name:
        class: Hgabka\EmailBundle\Layout\RecipientNameLayoutVar
        arguments: ['@hg_email.mail_builder']
        tags:
            - { name: hg_email.layout_var, priority: 105 }
        calls:
        - [setTranslator, ["@translator"]]

    hg_email.layout_var.recipient_email:
        class: Hgabka\EmailBundle\Layout\RecipientEmailLayoutVar
        arguments: ['@hg_email.mail_builder']
        tags:
            - { name: hg_email.layout_var, priority: 110 }
        calls:
        - [setTranslator, ["@translator"]]

    hg_email.layout_var.sender_name:
        class: Hgabka\EmailBundle\Layout\SenderNameLayoutVar
        arguments: ['@hg_email.mail_builder']
        tags:
            - { name: hg_email.layout_var, priority: 104 }
        calls:
        - [setTranslator, ["@translator"]]

    hg_email.layout_var.sender_email:
        class: Hgabka\EmailBundle\Layout\SenderEmailLayoutVar
        arguments: ['@hg_email.mail_builder']
        tags:
            - { name: hg_email.layout_var, priority: 109 }
        calls:
        - [setTranslator, ["@translator"]]

    hg_email.layout_var.subject:
        class: Hgabka\EmailBundle\Layout\SubjectLayoutVar
        tags:
            - { name: hg_email.layout_var, priority: 95 }
        calls:
        - [setTranslator, ["@translator"]]


    Hgabka\EmailBundle\Helper\MessageSender: "@hg_email.message_sender"
    Hgabka\EmailBundle\Helper\MailBuilder: "@hg_email.mail_builder"
    Hgabka\EmailBundle\Helper\TemplateTypeManager: "@hg_email.template_type_manager"
    Hgabka\EmailBundle\Helper\QueueManager: "@hg_email.queue_manager"
    Hgabka\EmailBundle\Helper\SubscriptionManager: '@hg_email.subscription_manager'
    Hgabka\EmailBundle\Helper\LayoutManager: '@hg_email.layout_manager'

    Hgabka\EmailBundle\Controller\MessageController:
        autowire: true
        autoconfigure: true
        tags: ['controller.service_arguments']

    Hgabka\EmailBundle\Controller\MessageListAdminController:
        autowire: true
        autoconfigure: true
        tags: ['controller.service_arguments']
        
    Hgabka\EmailBundle\Controller\EmailLayoutAdminController:
        autowire: true
        autoconfigure: true
        tags: ['controller.service_arguments']

    Hgabka\EmailBundle\Command\SendMessagesCommand:
        autowire: true
        autoconfigure: true

    Hgabka\EmailBundle\Command\SendEmailsCommand:
        autowire: true
        autoconfigure: true
        
    Hgabka\EmailBundle\Controller\EmailTemplateAdminController:
        autowire: true
        autoconfigure: true
        tags: ['controller.service_arguments']
        
    Hgabka\EmailBundle\Controller\MessageAdminController:
        autowire: true
        autoconfigure: true
        tags: ['controller.service_arguments']
        
    Hgabka\EmailBundle\Controller\SubscriberAdminController:
        autowire: true
        autoconfigure: true
        tags: ['controller.service_arguments']

    Hgabka\EmailBundle\EventListener\RedirectMailerSubscriber:
        autowire: true
        autoconfigure: true
        arguments:
            $redirectConfig: '%hg_email.redirect_config%'
            $debug: '%kernel.debug%'

    Hgabka\EmailBundle\EventListener\AddHeadersMailerSubscriber:
        autowire: true
        autoconfigure: true
        arguments:
            $headersConfig: '%hg_email.headers_config%'

    Hgabka\EmailBundle\EventListener\MailerEventSubscriber:
        autowire: true
        autoconfigure: true

    Hgabka\EmailBundle\Helper\MailHelper:
        autowire: true
        autoconfigure: true
